- name: Flutter action
  # You may pin to the exact commit or the version.
  # uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
  uses: subosito/flutter-action@v2.4.0
  with:
    # The Flutter version to make available on the path
    flutter-version: # optional, default is any
    # The Flutter build release channel
    channel: # optional, default is stable
    # Cache the Flutter SDK
    cache: # optional
    # Identifier for the Flutter SDK cache
    cache-key: # optional, default is flutter
    # Flutter SDK cache path
    cache-path: # optional, default is ${{ runner.tool_cache }}/flutter
    # The architecture of Flutter SDK executable (x64 or arm64)
    architecture: # optional, default is x64
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-java@v2
    with:
      distribution: 'zulu'
      java-version: '11'
  - uses: subosito/flutter-action@v2
    with:
      flutter-version: '2.10.4'
  - run: flutter pub get
  - run: flutter test
  - run: flutter build apk
  - run: flutter build appbundle
